### ISSUE TITLE
Explicitely map Njobs field to long

### ISSUE THREAD

**Issue by retzkek** [opensciencegrid/gracc-raw#1]

**Comment by retzkek** [comment]
Also `NodeCount`

**Comment by bbockelm** [comment]
I forget - is there an `int` (32-bit) type?  It seems quite unlikely that `NodeCount` needs to be 64-bit...

(not that it really matters too much...)

**Comment by retzkek** [comment]
There is (`integer`, as well as `short` and `byte`) - https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html

Don't think we'll be running jobs on the IoT, eh? :)

**Comment by bbockelm** [comment]
If you have a large enough aggregate, `NJobs` might overflow a 32-bit integer.  So, I'm willing to be cautious there: just seemed a little excessive for `NodeCount`.

**Comment by retzkek** [comment]
This was addressed way back with bf0b4d4
